import { FileEntry, StoredReport, StoredReportMeta } from '../models/models';

const DB_NAME = 'SmartStorageAnalyzerHistory';
// v2 splits one store into two: report metadata and report file listings.
//
// v1 kept the whole report — including every FileEntry — in a single record, so
// getAll() deserialized every listing just to render a list of dates and badges.
// On real reports that is ~1.8M objects resident in the tab, and the mitigation
// was a row cap that quietly dropped rows from the saved copy. Splitting the
// stores removes the reason for the cap: nothing loads a listing until something
// actually displays it.
const DB_VERSION = 2;
const META_STORE = 'reports';
const ENTRIES_STORE = 'reportEntries';
const MAX_REPORTS = 10;

// One report's file listing, stored on its own so it can be read — or evicted —
// independently of the metadata that the history list needs.
//
// Written in chunks of CHUNK_SIZE entries, keyed "<reportId>#<chunk>", all in
// one transaction (so a failed save still leaves nothing half-written). A single
// record holding a 190,000-row listing had to be structured-cloned in one piece,
// which could run the tab out of memory and surface as a misleading storage
// error. Listings saved before chunking are one record keyed by the bare report
// id; reads still accept that shape, so no database upgrade is needed.
interface StoredEntries {
  id: string;
  entries: FileEntry[];
}
const CHUNK_SIZE = 20000;

function chunkKey(reportId: string, index: number): string {
  // Zero-padded so the keys sort in chunk order.
  const n = String(index);
  return `${reportId}#${'000000'.substring(n.length)}${n}`;
}

// Every chunk key of one report, excluding the legacy single-record key.
function chunkRange(reportId: string): IDBKeyRange {
  return IDBKeyRange.bound(`${reportId}#`, `${reportId}#￿`);
}

export class ReportHistoryService {
  private openDb(): Promise<IDBDatabase> {
    return new Promise((resolve, reject) => {
      const req = indexedDB.open(DB_NAME, DB_VERSION);
      req.onupgradeneeded = (e) => {
        const db = (e.target as IDBOpenDBRequest).result;
        const tx = (e.target as IDBOpenDBRequest).transaction!;

        if (!db.objectStoreNames.contains(META_STORE)) {
          const store = db.createObjectStore(META_STORE, { keyPath: 'id' });
          store.createIndex('timestamp', 'timestamp', { unique: false });
        }
        if (!db.objectStoreNames.contains(ENTRIES_STORE)) {
          db.createObjectStore(ENTRIES_STORE, { keyPath: 'id' });
        }

        // Migrate v1 records in place: each held `entries` inline, so split each
        // one across the two stores. Done with a cursor inside the upgrade
        // transaction so a failure rolls the whole thing back rather than
        // leaving half-migrated history.
        //
        // Defensive on purpose: a report that fails to migrate keeps its inline
        // entries, and getEntries() below still reads that shape. Losing saved
        // history to a botched migration would be a worse outcome than carrying
        // one old record forward untouched.
        if (e.oldVersion > 0 && e.oldVersion < 2) {
          const meta = tx.objectStore(META_STORE);
          const entries = tx.objectStore(ENTRIES_STORE);
          const cursorReq = meta.openCursor();
          cursorReq.onsuccess = (ev) => {
            const cursor = (ev.target as IDBRequest<IDBCursorWithValue>).result;
            if (!cursor) return;
            const rec = cursor.value as StoredReport & { entriesTruncated?: boolean };
            if (Array.isArray(rec.entries)) {
              try {
                entries.put({ id: rec.id, entries: rec.entries });
                const { entries: _dropped, entriesTruncated: _old, ...rest } = rec;
                meta.put({
                  ...rest,
                  entryCount: rec.entries.length,
                  // v1's entriesTruncated meant "rows were filtered out of the
                  // saved copy", which is not what listingEvicted means. The
                  // listing IS present, just historically incomplete — and there
                  // is no way to recover the missing rows, so it is not flagged.
                  listingEvicted: false,
                });
              } catch {
                // Leave this record exactly as it was.
              }
            }
            cursor.continue();
          };
        }
      };
      req.onsuccess = (e) => resolve((e.target as IDBOpenDBRequest).result);
      req.onerror = (e) => reject((e.target as IDBOpenDBRequest).error);
    });
  }

  /**
   * Saves a report. The summary is written first and separately from the
   * listing, so a listing that cannot fit never costs the summary — losing a
   * scan's numbers to a storage limit would be far worse than losing its
   * per-file rows, which can be regenerated by scanning again.
   *
   * Resolves with what actually happened so the caller can tell the user.
   */
  async add(report: StoredReport): Promise<{ listingSaved: boolean; quotaExceeded: boolean }> {
    const db = await this.openDb();
    const meta: StoredReportMeta = {
      id: report.id,
      timestamp: report.timestamp,
      siteUrl: report.siteUrl,
      options: report.options,
      summary: report.summary,
      entryCount: report.entries.length,
    };

    try {
      await this.writeMeta(db, meta);
      try {
        await this.writeEntries(db, { id: report.id, entries: report.entries });
        return { listingSaved: true, quotaExceeded: false };
      } catch (err: any) {
        // Out of space. Free the OLDEST listings one at a time — their
        // summaries stay, so the history list and diffing are unaffected —
        // retrying after each, until the write fits or nothing is left to
        // free. (This used to free one listing, retry once, then give up even
        // when freeing a second would have made room.)
        if (!await isLikelyQuotaError(err)) {
          // Not a space problem (e.g. too large to serialize in one piece), so
          // freeing older listings wouldn't help. The summary is saved; mark
          // the listing as unavailable so View says so instead of failing.
          await this.writeMeta(db, { ...meta, listingEvicted: true });
          return { listingSaved: false, quotaExceeded: false };
        }
        for (;;) {
          const freed = await this.evictOldestListing(db, report.id);
          if (!freed) break;
          try {
            await this.writeEntries(db, { id: report.id, entries: report.entries });
            return { listingSaved: true, quotaExceeded: false };
          } catch (retryErr: any) {
            if (!await isLikelyQuotaError(retryErr)) {
              // Space was no longer the problem; report it as such.
              await this.writeMeta(db, { ...meta, listingEvicted: true });
              return { listingSaved: false, quotaExceeded: false };
            }
          }
        }
        // Still no room. The summary is already saved; record that this report
        // has no retrievable listing rather than leaving a View that fails.
        await this.writeMeta(db, { ...meta, listingEvicted: true });
        return { listingSaved: false, quotaExceeded: true };
      }
    } finally {
      db.close();
    }
  }

  private async writeMeta(db: IDBDatabase, meta: StoredReportMeta): Promise<void> {
    // Trimming happens here, against the metadata store, because that is what
    // MAX_REPORTS counts. A trimmed report's listing goes with it.
    const excessIds = await this.idsBeyondLimit(db, meta.id);
    return runTx(db, [META_STORE, ENTRIES_STORE], 'readwrite', (tx) => {
      const store = tx.objectStore(META_STORE);
      const entries = tx.objectStore(ENTRIES_STORE);
      for (const id of excessIds) {
        store.delete(id);
        deleteListing(entries, id);
      }
      store.put(meta);
    });
  }

  private async writeEntries(db: IDBDatabase, payload: StoredEntries): Promise<void> {
    return runTx(db, [ENTRIES_STORE], 'readwrite', (tx) => {
      const store = tx.objectStore(ENTRIES_STORE);
      // Replacing, not appending: clear any earlier copy in either shape.
      deleteListing(store, payload.id);
      for (let i = 0, chunk = 0; i < payload.entries.length || chunk === 0; i += CHUNK_SIZE, chunk++) {
        store.put({ id: chunkKey(payload.id, chunk), entries: payload.entries.slice(i, i + CHUNK_SIZE) });
      }
    });
  }

  // Oldest-first ids that must go to keep the store at MAX_REPORTS once
  // `incomingId` is added. Returns [] when it is already a known id (an
  // overwrite doesn't grow the store).
  private async idsBeyondLimit(db: IDBDatabase, incomingId: string): Promise<string[]> {
    const existing = await this.getAll(db);
    if (existing.some((r) => r.id === incomingId)) return [];
    // getAll is newest-first, so the tail is oldest.
    const overBy = existing.length - MAX_REPORTS + 1;
    if (overBy <= 0) return [];
    return existing.slice(existing.length - overBy).map((r) => r.id);
  }

  // Deletes the single oldest stored listing, keeping its metadata. Returns
  // false when there is nothing left to free. One at a time: the next write
  // attempt may well succeed now, and discarding more history than necessary
  // is not recoverable. `exceptId` is the report currently being saved.
  private async evictOldestListing(db: IDBDatabase, exceptId: string): Promise<boolean> {
    const all = await this.getAll(db);
    // getAll is newest-first; the last candidate is the oldest.
    const candidates = all.filter((r) => r.id !== exceptId && !r.listingEvicted && r.entryCount > 0);
    const victim = candidates[candidates.length - 1];
    if (!victim) return false;
    await runTx(db, [META_STORE, ENTRIES_STORE], 'readwrite', (tx) => {
      deleteListing(tx.objectStore(ENTRIES_STORE), victim.id);
      tx.objectStore(META_STORE).put({ ...victim, listingEvicted: true });
    });
    return true;
  }

  /** Report summaries, newest first. Never loads a file listing. */
  async getAll(existingDb?: IDBDatabase): Promise<StoredReportMeta[]> {
    const db = existingDb ?? await this.openDb();
    try {
      const rows = await new Promise<StoredReportMeta[]>((resolve, reject) => {
        const tx = db.transaction(META_STORE, 'readonly');
        const req = tx.objectStore(META_STORE).index('timestamp').getAll();
        req.onsuccess = () => resolve(req.result as StoredReportMeta[]);
        req.onerror = () => reject(req.error);
      });
      return rows.reverse(); // newest first
    } finally {
      if (!existingDb) db.close();
    }
  }

  /**
   * One report's file listing, or null when it isn't stored (evicted for space,
   * or never fit). Callers must handle null — it is a normal state, not an error.
   */
  async getEntries(id: string): Promise<FileEntry[] | null> {
    const db = await this.openDb();
    try {
      return await new Promise<FileEntry[] | null>((resolve, reject) => {
        const tx = db.transaction(ENTRIES_STORE, 'readonly');
        const store = tx.objectStore(ENTRIES_STORE);
        // Chunked listing first; fall back to a pre-chunking single record.
        const chunksReq = store.getAll(chunkRange(id));
        chunksReq.onsuccess = () => {
          const chunks = chunksReq.result as StoredEntries[];
          if (chunks.length > 0) {
            // getAll returns records in key order, which is chunk order.
            const all: FileEntry[] = [];
            for (const c of chunks) for (const e of c.entries) all.push(e);
            resolve(all);
            return;
          }
          const legacyReq = store.get(id);
          legacyReq.onsuccess = () => {
            const rec = legacyReq.result as StoredEntries | undefined;
            resolve(rec?.entries ?? null);
          };
          legacyReq.onerror = () => reject(legacyReq.error);
        };
        chunksReq.onerror = () => reject(chunksReq.error);
      });
    } finally {
      db.close();
    }
  }

  async delete(id: string): Promise<void> {
    const db = await this.openDb();
    try {
      await runTx(db, [META_STORE, ENTRIES_STORE], 'readwrite', (tx) => {
        tx.objectStore(META_STORE).delete(id);
        deleteListing(tx.objectStore(ENTRIES_STORE), id);
      });
    } finally {
      db.close();
    }
  }
}

// Removes a report's listing in both shapes: its chunks and any legacy
// single record.
function deleteListing(store: IDBObjectStore, reportId: string): void {
  store.delete(reportId);
  store.delete(chunkRange(reportId));
}

// Runs a transaction and settles on its outcome.
//
// Every failure mode is wired, which the previous implementation did not do and
// which is why a full disk could hang the UI silently: `put` was called inside a
// request callback, so if it threw synchronously (DataCloneError, or the tx
// already aborting) NOTHING rejected the promise — the caller awaited forever,
// so neither the report nor the "could not be saved" warning ever appeared.
//   - a synchronous throw inside `work`  -> reject (was: hang)
//   - tx.onabort, which is what a quota failure fires -> reject (was: hang)
//   - tx.onerror -> reject
function runTx(
  db: IDBDatabase,
  stores: string[],
  mode: IDBTransactionMode,
  work: (tx: IDBTransaction) => void,
): Promise<void> {
  return new Promise((resolve, reject) => {
    let tx: IDBTransaction;
    try {
      tx = db.transaction(stores, mode);
    } catch (err) {
      reject(err);
      return;
    }
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
    tx.onabort = () => reject(tx.error ?? new DOMException('Transaction aborted', 'AbortError'));
    try {
      work(tx);
    } catch (err) {
      // The abort handler above may also fire; whichever lands first wins and
      // the other is a no-op on a settled promise.
      try { tx.abort(); } catch { /* already aborting */ }
      reject(err);
    }
  });
}

// Quota exhaustion arrives under more than one name depending on the browser,
// and the transaction-level abort often carries no error at all — so a null
// error during a large write is treated as quota too. Guessing wrong here only
// changes which recovery path runs, and both are safe.
function isQuotaError(err: any): boolean {
  if (!err) return true;
  const name = String(err.name ?? '');
  return name === 'QuotaExceededError'
    || name === 'NS_ERROR_DOM_QUOTA_REACHED'
    || name === 'AbortError'
    || name === 'UnknownError';
}

// isQuotaError plus a sanity check for the ambiguous names. Chromium also
// reports an out-of-memory failure serializing one huge record as
// UnknownError; treating that as "disk full" deleted older reports' listings
// for nothing. When the browser says most of the quota is still free, it
// isn't a quota problem.
async function isLikelyQuotaError(err: any): Promise<boolean> {
  if (!isQuotaError(err)) return false;
  const name = String(err?.name ?? '');
  if (name === 'QuotaExceededError' || name === 'NS_ERROR_DOM_QUOTA_REACHED') return true;
  try {
    const est = await navigator.storage?.estimate?.();
    if (est?.quota && est.usage != null && est.usage < est.quota * 0.5) return false;
  } catch {
    // No estimate available — keep the original, cautious classification.
  }
  return true;
}
