import { FileEntry, StoredReport, StoredReportMeta } from '../models/models';

const DB_NAME = 'SmartStorageAnalyzerHistory';
// v2 splits one store into two: report metadata and report file listings.
//
// v1 kept the whole report — including every FileEntry — in a single record, so
// getAll() deserialized every listing just to render a list of dates and badges.
// On real reports that is ~1.8M objects resident in the tab, and the mitigation
// was a row cap that quietly dropped rows from the saved copy. Splitting the
// stores removes the reason for the cap: nothing loads a listing until something
// actually displays it.
const DB_VERSION = 2;
const META_STORE = 'reports';
const ENTRIES_STORE = 'reportEntries';
const MAX_REPORTS = 10;

// One report's file listing, stored on its own so it can be read — or evicted —
// independently of the metadata that the history list needs.
interface StoredEntries {
  id: string;
  entries: FileEntry[];
}

export class ReportHistoryService {
  private openDb(): Promise<IDBDatabase> {
    return new Promise((resolve, reject) => {
      const req = indexedDB.open(DB_NAME, DB_VERSION);
      req.onupgradeneeded = (e) => {
        const db = (e.target as IDBOpenDBRequest).result;
        const tx = (e.target as IDBOpenDBRequest).transaction!;

        if (!db.objectStoreNames.contains(META_STORE)) {
          const store = db.createObjectStore(META_STORE, { keyPath: 'id' });
          store.createIndex('timestamp', 'timestamp', { unique: false });
        }
        if (!db.objectStoreNames.contains(ENTRIES_STORE)) {
          db.createObjectStore(ENTRIES_STORE, { keyPath: 'id' });
        }

        // Migrate v1 records in place: each held `entries` inline, so split each
        // one across the two stores. Done with a cursor inside the upgrade
        // transaction so a failure rolls the whole thing back rather than
        // leaving half-migrated history.
        //
        // Defensive on purpose: a report that fails to migrate keeps its inline
        // entries, and getEntries() below still reads that shape. Losing saved
        // history to a botched migration would be a worse outcome than carrying
        // one old record forward untouched.
        if (e.oldVersion > 0 && e.oldVersion < 2) {
          const meta = tx.objectStore(META_STORE);
          const entries = tx.objectStore(ENTRIES_STORE);
          const cursorReq = meta.openCursor();
          cursorReq.onsuccess = (ev) => {
            const cursor = (ev.target as IDBRequest<IDBCursorWithValue>).result;
            if (!cursor) return;
            const rec = cursor.value as StoredReport & { entriesTruncated?: boolean };
            if (Array.isArray(rec.entries)) {
              try {
                entries.put({ id: rec.id, entries: rec.entries });
                const { entries: _dropped, entriesTruncated: _old, ...rest } = rec;
                meta.put({
                  ...rest,
                  entryCount: rec.entries.length,
                  // v1's entriesTruncated meant "rows were filtered out of the
                  // saved copy", which is not what listingEvicted means. The
                  // listing IS present, just historically incomplete — and there
                  // is no way to recover the missing rows, so it is not flagged.
                  listingEvicted: false,
                });
              } catch {
                // Leave this record exactly as it was.
              }
            }
            cursor.continue();
          };
        }
      };
      req.onsuccess = (e) => resolve((e.target as IDBOpenDBRequest).result);
      req.onerror = (e) => reject((e.target as IDBOpenDBRequest).error);
    });
  }

  /**
   * Saves a report. The summary is written first and separately from the
   * listing, so a listing that cannot fit never costs the summary — losing a
   * scan's numbers to a storage limit would be far worse than losing its
   * per-file rows, which can be regenerated by scanning again.
   *
   * Resolves with what actually happened so the caller can tell the user.
   */
  async add(report: StoredReport): Promise<{ listingSaved: boolean; quotaExceeded: boolean }> {
    const db = await this.openDb();
    const meta: StoredReportMeta = {
      id: report.id,
      timestamp: report.timestamp,
      siteUrl: report.siteUrl,
      options: report.options,
      summary: report.summary,
      entryCount: report.entries.length,
    };

    try {
      await this.writeMeta(db, meta);
      try {
        await this.writeEntries(db, { id: report.id, entries: report.entries });
        return { listingSaved: true, quotaExceeded: false };
      } catch (err: any) {
        // Out of space. Free the OLDEST listings — their summaries stay, so the
        // history list and diffing are unaffected — and try once more.
        if (!isQuotaError(err)) throw err;
        const freed = await this.evictOldestListings(db, report.id);
        if (freed > 0) {
          try {
            await this.writeEntries(db, { id: report.id, entries: report.entries });
            return { listingSaved: true, quotaExceeded: false };
          } catch (retryErr: any) {
            if (!isQuotaError(retryErr)) throw retryErr;
          }
        }
        // Still no room. The summary is already saved; record that this report
        // has no retrievable listing rather than leaving a View that fails.
        await this.writeMeta(db, { ...meta, listingEvicted: true });
        return { listingSaved: false, quotaExceeded: true };
      }
    } finally {
      db.close();
    }
  }

  private async writeMeta(db: IDBDatabase, meta: StoredReportMeta): Promise<void> {
    // Trimming happens here, against the metadata store, because that is what
    // MAX_REPORTS counts. A trimmed report's listing goes with it.
    const excessIds = await this.idsBeyondLimit(db, meta.id);
    return runTx(db, [META_STORE, ENTRIES_STORE], 'readwrite', (tx) => {
      const store = tx.objectStore(META_STORE);
      const entries = tx.objectStore(ENTRIES_STORE);
      for (const id of excessIds) {
        store.delete(id);
        entries.delete(id);
      }
      store.put(meta);
    });
  }

  private async writeEntries(db: IDBDatabase, payload: StoredEntries): Promise<void> {
    return runTx(db, [ENTRIES_STORE], 'readwrite', (tx) => {
      tx.objectStore(ENTRIES_STORE).put(payload);
    });
  }

  // Oldest-first ids that must go to keep the store at MAX_REPORTS once
  // `incomingId` is added. Returns [] when it is already a known id (an
  // overwrite doesn't grow the store).
  private async idsBeyondLimit(db: IDBDatabase, incomingId: string): Promise<string[]> {
    const existing = await this.getAll(db);
    if (existing.some((r) => r.id === incomingId)) return [];
    // getAll is newest-first, so the tail is oldest.
    const overBy = existing.length - MAX_REPORTS + 1;
    if (overBy <= 0) return [];
    return existing.slice(existing.length - overBy).map((r) => r.id);
  }

  // Deletes stored listings oldest-first, keeping their metadata, and returns
  // how many were freed. `exceptId` is the report currently being saved.
  private async evictOldestListings(db: IDBDatabase, exceptId: string): Promise<number> {
    const all = await this.getAll(db);
    // Oldest first, and only those that still have a listing to free.
    const candidates = all
      .filter((r) => r.id !== exceptId && !r.listingEvicted && r.entryCount > 0)
      .reverse();
    let freed = 0;
    for (const victim of candidates) {
      await runTx(db, [META_STORE, ENTRIES_STORE], 'readwrite', (tx) => {
        tx.objectStore(ENTRIES_STORE).delete(victim.id);
        tx.objectStore(META_STORE).put({ ...victim, listingEvicted: true });
      });
      freed++;
      // One at a time: the next write attempt may well succeed now, and
      // discarding more history than necessary is not recoverable.
      break;
    }
    return freed;
  }

  /** Report summaries, newest first. Never loads a file listing. */
  async getAll(existingDb?: IDBDatabase): Promise<StoredReportMeta[]> {
    const db = existingDb ?? await this.openDb();
    try {
      const rows = await new Promise<StoredReportMeta[]>((resolve, reject) => {
        const tx = db.transaction(META_STORE, 'readonly');
        const req = tx.objectStore(META_STORE).index('timestamp').getAll();
        req.onsuccess = () => resolve(req.result as StoredReportMeta[]);
        req.onerror = () => reject(req.error);
      });
      return rows.reverse(); // newest first
    } finally {
      if (!existingDb) db.close();
    }
  }

  /**
   * One report's file listing, or null when it isn't stored (evicted for space,
   * or never fit). Callers must handle null — it is a normal state, not an error.
   */
  async getEntries(id: string): Promise<FileEntry[] | null> {
    const db = await this.openDb();
    try {
      return await new Promise<FileEntry[] | null>((resolve, reject) => {
        const tx = db.transaction(ENTRIES_STORE, 'readonly');
        const req = tx.objectStore(ENTRIES_STORE).get(id);
        req.onsuccess = () => {
          const rec = req.result as StoredEntries | undefined;
          resolve(rec?.entries ?? null);
        };
        req.onerror = () => reject(req.error);
      });
    } finally {
      db.close();
    }
  }

  async delete(id: string): Promise<void> {
    const db = await this.openDb();
    try {
      await runTx(db, [META_STORE, ENTRIES_STORE], 'readwrite', (tx) => {
        tx.objectStore(META_STORE).delete(id);
        tx.objectStore(ENTRIES_STORE).delete(id);
      });
    } finally {
      db.close();
    }
  }
}

// Runs a transaction and settles on its outcome.
//
// Every failure mode is wired, which the previous implementation did not do and
// which is why a full disk could hang the UI silently: `put` was called inside a
// request callback, so if it threw synchronously (DataCloneError, or the tx
// already aborting) NOTHING rejected the promise — the caller awaited forever,
// so neither the report nor the "could not be saved" warning ever appeared.
//   - a synchronous throw inside `work`  -> reject (was: hang)
//   - tx.onabort, which is what a quota failure fires -> reject (was: hang)
//   - tx.onerror -> reject
function runTx(
  db: IDBDatabase,
  stores: string[],
  mode: IDBTransactionMode,
  work: (tx: IDBTransaction) => void,
): Promise<void> {
  return new Promise((resolve, reject) => {
    let tx: IDBTransaction;
    try {
      tx = db.transaction(stores, mode);
    } catch (err) {
      reject(err);
      return;
    }
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
    tx.onabort = () => reject(tx.error ?? new DOMException('Transaction aborted', 'AbortError'));
    try {
      work(tx);
    } catch (err) {
      // The abort handler above may also fire; whichever lands first wins and
      // the other is a no-op on a settled promise.
      try { tx.abort(); } catch { /* already aborting */ }
      reject(err);
    }
  });
}

// Quota exhaustion arrives under more than one name depending on the browser,
// and the transaction-level abort often carries no error at all — so a null
// error during a large write is treated as quota too. Guessing wrong here only
// changes which recovery path runs, and both are safe.
function isQuotaError(err: any): boolean {
  if (!err) return true;
  const name = String(err.name ?? '');
  return name === 'QuotaExceededError'
    || name === 'NS_ERROR_DOM_QUOTA_REACHED'
    || name === 'AbortError'
    || name === 'UnknownError';
}
